-- MySQL Script generated by MySQL Workbench
-- 02/21/17 15:29:35
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema r_bot
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema r_bot
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `r_bot` DEFAULT CHARACTER SET utf8 ;
USE `r_bot` ;

-- -----------------------------------------------------
-- Table `r_bot`.`rmemform`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `r_bot`.`rmemform` (
  `position_title` VARCHAR(20) NOT NULL,
  `seat_location` VARCHAR(20) NOT NULL,
  `cgi_submit_dt` DATETIME NOT NULL,
  `num_resource_need` INT(11) NOT NULL,
  `proj_start_dt` DATETIME NOT NULL,
  `tmfp` VARCHAR(2) NULL DEFAULT NULL,
  `job_type` VARCHAR(20) NOT NULL,
  `est_resource_start_dt` DATETIME NOT NULL,
  `est_resource_end_dt` DATETIME NOT NULL,
  `proj_client` VARCHAR(20) NOT NULL,
  `confidence` INT(11) NOT NULL,
  `hiring_manager` VARCHAR(50) NOT NULL,
  `senior_manager` VARCHAR(50) NOT NULL,
  `cgi_engage_manager` VARCHAR(50) NOT NULL,
  `proj_code` INT(11) NOT NULL,
  `target_salary` INT(11) NOT NULL,
  `rate_crd_cat_lvl` VARCHAR(20) NOT NULL,
  `position_desc` TEXT NULL DEFAULT NULL,
  `recommended_hiring` VARCHAR(20) NULL DEFAULT NULL,
  `notes` TEXT NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `r_bot`.`rmhrform`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `r_bot`.`rmhrform` (
  `position_title` VARCHAR(20) NOT NULL,
  `seat_location` VARCHAR(20) NOT NULL,
  `cgi_submit_dt` DATETIME NOT NULL,
  `num_resource_need` INT(11) NOT NULL,
  `proj_start_dt` DATETIME NOT NULL,
  `tmfp` VARCHAR(2) NULL DEFAULT NULL,
  `job_type` VARCHAR(20) NOT NULL,
  `est_resource_start_dt` DATETIME NOT NULL,
  `est_resource_end_dt` DATETIME NOT NULL,
  `proj_client` VARCHAR(20) NOT NULL,
  `confidence` INT(11) NOT NULL,
  `hiring_manager` VARCHAR(50) NOT NULL,
  `senior_manager` VARCHAR(50) NOT NULL,
  `cgi_engage_manager` VARCHAR(50) NOT NULL,
  `proj_code` INT(11) NOT NULL,
  `target_salary` INT(11) NOT NULL,
  `rate_crd_cat_lvl` VARCHAR(20) NOT NULL,
  `position_desc` TEXT NULL DEFAULT NULL,
  `recommended_hiring` VARCHAR(20) NULL DEFAULT NULL,
  `notes` TEXT NULL DEFAULT NULL,
  `so_number` VARCHAR(40) NULL DEFAULT NULL,
  `comments` TEXT NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `r_bot`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `r_bot`.`users` (
  `user_id` MEDIUMINT(8) UNSIGNED NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(20) NOT NULL,
  `last_name` VARCHAR(40) NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `email` VARCHAR(60) NOT NULL,
  `password` VARBINARY(250) NULL DEFAULT NULL,
  `user_type` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `r_bot`.`vendor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `r_bot`.`vendor` (
  `first_name` VARCHAR(20) NOT NULL,
  `last_name` VARCHAR(40) NOT NULL,
  `emp_id` INT(11) NOT NULL,
  PRIMARY KEY (`emp_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
