-- MySQL Script generated by MySQL Workbench
-- 03/29/17 09:02:43
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema r_bot
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema r_bot
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `r_bot` DEFAULT CHARACTER SET latin1 ;
USE `r_bot` ;

-- -----------------------------------------------------
-- Table `r_bot`.`files`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `r_bot`.`files` ;

CREATE TABLE IF NOT EXISTS `r_bot`.`files` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `fileName` VARCHAR(60) NOT NULL,
  `file_type` VARCHAR(60) NOT NULL,
  `file_size` INT(10) UNSIGNED NOT NULL,
  `fileActual` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = MyISAM
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `r_bot`.`rmemform`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `r_bot`.`rmemform` ;

CREATE TABLE IF NOT EXISTS `r_bot`.`rmemform` (
  `position_title` VARCHAR(20) NOT NULL,
  `seat_location` VARCHAR(20) NOT NULL,
  `num_resource_need` INT(11) NOT NULL,
  `tmfp` VARCHAR(2) NULL DEFAULT NULL,
  `job_type` VARCHAR(20) NOT NULL,
  `proj_client` VARCHAR(20) NOT NULL,
  `hiring_manager` VARCHAR(50) NOT NULL,
  `senior_manager` VARCHAR(50) NOT NULL,
  `cgi_engage_manager` VARCHAR(50) NOT NULL,
  `target_salary` INT(11) NOT NULL,
  `rate_crd_cat_lvl` VARCHAR(20) NOT NULL,
  `position_desc` TEXT NULL DEFAULT NULL,
  `recommended_hiring` VARCHAR(20) NULL DEFAULT NULL,
  `notes` TEXT NULL DEFAULT NULL,
  `lastUpdated` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `cgi_submit_dt` DATE NULL DEFAULT NULL,
  `proj_start_dt` DATE NULL DEFAULT NULL,
  `est_resource_start_dt` DATE NULL DEFAULT NULL,
  `est_resource_end_dt` DATE NULL DEFAULT NULL,
  `confidence` VARCHAR(5) NULL DEFAULT NULL,
  `proj_code` INT(20) NOT NULL,
  `so_number` VARCHAR(40) NULL DEFAULT NULL,
  `comments` TEXT NULL DEFAULT NULL,
  `RM_ID` INT(8) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`RM_ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 19
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `r_bot`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `r_bot`.`users` ;

CREATE TABLE IF NOT EXISTS `r_bot`.`users` (
  `user_id` MEDIUMINT(8) UNSIGNED NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(20) NOT NULL,
  `last_name` VARCHAR(40) NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `email` VARCHAR(60) NOT NULL,
  `password` VARBINARY(250) NULL DEFAULT NULL,
  `user_type` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `r_bot`.`vendor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `r_bot`.`vendor` ;

CREATE TABLE IF NOT EXISTS `r_bot`.`vendor` (
  `name` VARCHAR(40) NOT NULL,
  `phone_number` VARCHAR(40) NOT NULL,
  `best_call_time` VARCHAR(40) NOT NULL,
  `description` TEXT NOT NULL,
  `visa_status` VARCHAR(40) NOT NULL,
  `it_exp` VARCHAR(40) NOT NULL,
  `relevant_exp` VARCHAR(40) NOT NULL,
  `V_ID` INT(10) NOT NULL AUTO_INCREMENT,
  `so_number` VARCHAR(40) NULL DEFAULT NULL,
  `feedback` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`V_ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
